substitutions:
  _REGION: ${_REGION}
  _IMAGE: "${_ARTIFACT_REGISTRY_URL}/dbt_app:${COMMIT_SHA}" 

steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker image'
    args: ['build', '-t', '$_IMAGE', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker image to Artifact Registry'
    args: ['push', '$_IMAGE']