substitutions:
  _IMAGE: "${_ARTIFACT_REGISTRY_URL}/dbt_app:${COMMIT_SHA}" 

steps:
  - name: 'alpine'
    id: 'image name'
    entrypoint: 'sh'  
    args: 
    - '-c'
    - | 
        echo "***********************"
        echo "$_IMAGE"
        echo "***********************"

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker image'
    args: ['build', '-t', '$_IMAGE', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker image to Artifact Registry'
    args: ['push', '$_IMAGE']
  
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Trigger CD pipeline'
    args: [
      'builds',
      'triggers',
      'run',
      'dbt-cd-trigger-test',
      '--branch', '$_BRANCH_NAME',
      '--project', '$_PROJECT_ID'
    ]
      
options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s